metadata:
  org: github.com/igalarzab/homelab
  maintainer: Jose Galarza

settings:
  kubeContext: saturn

namespaces:
  cert-manager:
  cloudflare-ddns:
  external-dns:
  home-assistant:
  jdownloader:
  keel:
  kube-system:
  mosquitto:
  n8n:
  plex:
  pocket-id:
  traefik:

helmRepos:
  bitnami: https://charts.bitnami.com/bitnami
  bjw-s: https://bjw-s-labs.github.io/helm-charts
  containeroo: https://charts.containeroo.ch
  csi-driver-smb: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
  external-dns: https://kubernetes-sigs.github.io/external-dns/
  metrics-server: https://kubernetes-sigs.github.io/metrics-server/
  jetstack: https://charts.jetstack.io
  keel: https://charts.keel.sh
  traefik: https://traefik.github.io/charts

appsTemplates:
  default: &default
    enabled: true
    protected: false
    test: false
    wait: true

apps:
  csi-driver-smb:
    <<: *default
    chart: csi-driver-smb/csi-driver-smb
    version: "v1.19.1"
    namespace: kube-system
    priority: -109
  csi-driver-hostpath:
    <<: *default
    chart: containeroo/local-path-provisioner
    version: "0.0.33"
    namespace: kube-system
    priority: -108
  csi-driver-proxmox:
    <<: *default
    chart: oci://ghcr.io/sergelogvinov/charts/proxmox-csi-plugin
    version: "0.5.1"
    namespace: kube-system
    valuesFile: csi-driver-proxmox/values.yml
    priority: -107
  multus-cni:
    <<: *default
    chart: bitnami/multus-cni
    version: "2.2.21"
    namespace: kube-system
    valuesFile: multus-cni/values.yml
    priority: -106
  metrics-server:
    <<: *default
    chart: metrics-server/metrics-server
    version: "3.13.0"
    namespace: kube-system
    valuesFile: metrics-server/values.yml
    priority: -105
  cert-manager:
    <<: *default
    chart: jetstack/cert-manager
    version: "v1.19.2"
    namespace: cert-manager
    valuesFile: cert-manager/values.yml
    priority: -99
    hooks:
      postInstall: cert-manager/post-install.yml
  external-dns:
    <<: *default
    chart: external-dns/external-dns
    version: "1.19.0"
    namespace: external-dns
    valuesFile: external-dns/values.yml
    priority: -98
  traefik:
    <<: *default
    chart: traefik/traefik
    version: "v37.4.0"
    namespace: traefik
    valuesFile: traefik/values.yml
    priority: -97
  pocket-id:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: pocket-id
    valuesFile: pocket-id/values.yml
    priority: -96
  keel:
    <<: *default
    chart: keel/keel
    version: "1.0.5"
    namespace: keel
    valuesFile: keel/values.yml
    priority: -95
  cloudflare-ddns:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: cloudflare-ddns
    valuesFile: cloudflare-ddns/values.yml
    priority: -94
  n8n:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: n8n
    valuesFile: n8n/values.yml
    priority: -79
  jdownloader:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: jdownloader
    valuesFile: jdownloader/values.yml
    priority: -78
  plex:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: plex
    valuesFile: plex/values.yml
    priority: -69
  mosquitto:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: mosquitto
    valuesFile: mosquitto/values.yml
    priority: -59
  zigbee2mqtt:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: home-assistant
    valuesFile: home-assistant/zigbee2mqtt.values.yml
    priority: -58
  node-red:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: home-assistant
    valuesFile: home-assistant/nodered.values.yml
    priority: -57
  esphome:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: home-assistant
    valuesFile: home-assistant/esphome.values.yml
    priority: -56
  home-assistant:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: home-assistant
    valuesFile: home-assistant/home-assistant.values.yml
    priority: -55
