metadata:
  org: github.com/igalarzab/homelab
  maintainer: Jose Galarza

settings:
  kubeContext: jupyter

namespaces:
  cert-manager:
  external-dns:
  github-actions:
  keel:
  kube-system:
  pocket-id:
  traefik:

helmRepos:
  bjw-s: https://bjw-s-labs.github.io/helm-charts
  containeroo: https://charts.containeroo.ch
  external-dns: https://kubernetes-sigs.github.io/external-dns/
  metrics-server: https://kubernetes-sigs.github.io/metrics-server/
  jetstack: https://charts.jetstack.io
  keel: https://charts.keel.sh
  traefik: https://traefik.github.io/charts

appsTemplates:
  default: &default
    enabled: true
    protected: false
    test: false
    wait: true

apps:
  csi-driver-hostpath:
    <<: *default
    chart: containeroo/local-path-provisioner
    version: "0.0.33"
    namespace: kube-system
    valuesFile: csi-driver-hostpath/values.yml
    priority: -109
    hooks:
      postInstall: csi-driver-hostpath/post-install.yml
  metrics-server:
    <<: *default
    chart: metrics-server/metrics-server
    version: "3.13.0"
    namespace: kube-system
    valuesFile: metrics-server/values.yml
    priority: -108
  cert-manager:
    <<: *default
    chart: jetstack/cert-manager
    version: "v1.19.2"
    namespace: cert-manager
    valuesFile: cert-manager/values.yml
    priority: -99
    hooks:
      postInstall: cert-manager/post-install.yml
      postUpgrade: cert-manager/post-install.yml
  external-dns:
    <<: *default
    chart: external-dns/external-dns
    version: "1.19.0"
    namespace: external-dns
    valuesFile: external-dns/values.yml
    priority: -98
  traefik:
    <<: *default
    chart: traefik/traefik
    version: "v37.4.0"
    namespace: traefik
    valuesFile: traefik/values.yml
    priority: -97
  pocket-id:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: pocket-id
    valuesFile: pocket-id/values.yml
    priority: -96
  keel:
    <<: *default
    chart: keel/keel
    version: "1.0.5"
    namespace: keel
    valuesFile: keel/values.yml
    priority: -95
  github-actions:
    <<: *default
    chart: bjw-s/app-template
    version: "4.5.0"
    namespace: github-actions
    valuesFile: github-actions/values.yml
    priority: -59
