apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-persistent-path
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  pathPattern: "{{ .PVC.Name }}/{{ .PVName }}"
