---
- hosts: jupyter
  gather_facts: yes
  vars:
    enable_ufw: true
    cluster_name: jupyter
    k8s_api_server_san: "{{ jupyter_k8s_api_server_san }}"
  roles:
    - role: base
    - role: containerd
    - role: kubeadm
