---
- hosts: saturn
  gather_facts: yes
  vars:
    enable_ufw: false
    cluster_name: saturn
    k8s_api_server_san: "{{ saturn_k8s_api_server_san }}"
  roles:
    - role: base
    - role: containerd
    - role: kubeadm
