substitutions:
  name: bedroom-ac
  friendly_name: Bedroom AC
  area: Bedroom
  remote_temp_sensor: sensor.bedroom_thermometer_temperature

packages:
  mitsubishi-ac: !include templates/mitsubishi-ac.yaml

bluetooth_proxy:
  active: true
