---
docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_apt_key_path: /etc/apt/keyrings/docker.gpg
docker_apt_repo_url: "https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
